FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src 

# Copy and restore IdentityService project
COPY IdentityService/*.csproj IdentityService/
RUN dotnet restore IdentityService/IdentityService.csproj

# Copy the remaining code
COPY IdentityService/ IdentityService/

RUN dotnet publish IdentityService/IdentityService.csproj -c Release -o /app 

# Phase #2, Build final image 

FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS release

WORKDIR /app

COPY --from=build /app .

EXPOSE 80 443

ENV ASPNETCORE_URLS=http://+:80;https://+:443

ENTRYPOINT ["dotnet", "./IdentityService.dll"]
