FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src 

# Copy and restore ClientApplication project
COPY ClientApplication/*.csproj ClientApplication/
RUN dotnet restore ClientApplication/ClientApplication.csproj

# Copy the remaining code
COPY ClientApplication/ ClientApplication/

RUN dotnet publish ClientApplication/ClientApplication.csproj -c Release -o /app 

# Phase #2, Build final image 

FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS release

WORKDIR /app

COPY --from=build /app .

EXPOSE 80 443

ENV ASPNETCORE_URLS=http://+:80;https://+:443

ENTRYPOINT ["dotnet", "./ClientApplication.dll"]
